name: Deploy Worker
on:
  push:
    tags:
      - "v*"
  workflow_dispatch:  # 添加这一行

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
        with:
          node-version: 20
      - uses: pnpm/action-setup@v4
        with:
          version: 9

      - name: Install dependencies
        run: pnpm install

      - name: Run deploy script
        env:
          CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}

          CUSTOM_DOMAIN: ${{ secrets.CUSTOM_DOMAIN }}

          BETTER_AUTH_SECRET: ${{ secrets.BETTER_AUTH_SECRET }}
          BETTER_AUTH_URL: ${{ secrets.BETTER_AUTH_URL }}
          BETTER_AUTH_GITHUB_CLIENT_ID: ${{ secrets.BETTER_AUTH_GITHUB_CLIENT_ID }}
          BETTER_AUTH_GITHUB_CLIENT_SECRET: ${{ secrets.BETTER_AUTH_GITHUB_CLIENT_SECRET }}
          RESEND_API_KEY: ${{ secrets.RESEND_API_KEY }}
          RESEND_SENDER_ADDRESS: ${{ secrets.RESEND_SENDER_ADDRESS }}

          NEXT_PUBLIC_MAX_FILE_MB: ${{ secrets.NEXT_PUBLIC_MAX_FILE_MB }}
          NEXT_PUBLIC_BUCKET_ADDRESS: ${{ secrets.NEXT_PUBLIC_BUCKET_ADDRESS }}
        run: pnpm tsx scripts/deploy/index.ts
